
os: linux

lagnuage: go

go:
  - 1.14.x

services:
  - docker

script:
  - go test -v ./...
  - CGO_ENABLED=0 go build -o demo
  
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
